### ISSUE TITLE
How can I save the model once trained for later use.

### ISSUE THREAD

**Issue by shivamkantival** [ulfbiallas/npm-mlp#1]
How can i save the model once trained to be used later so that i need not train the neural network with thousands of cases every time i want to use this classifier.

**Comment by ulfbiallas** [comment]
Moin @shivamkantival,
I just published version 1.1.0 which offers two new methods _exportToJson_ and _setWeights_ which should fulfill your needs :-)

Thanks for your issue!

Ulf
