### ISSUE TITLE
Cannot read property 'w' of undefined

### ISSUE THREAD

**Issue by legacyWork** [ulfbiallas/npm-mlp#3]
var MLP = require('mlp');
var mlp = new MLP(25,1);
mlp.addHiddenLayer(5);
mlp.addHiddenLayer(5);

```
    mlp.addToTrainingSet([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],[1])
```

var learnRate = 0.5;
var error = Number.MAX_VALUE;
while (error > 0.01) {
    console.log(error + " was the error")
    error = mlp.train(learnRate);
}

Causes the error.

**Comment by ulfbiallas** [comment]
Hi, 
you need to call mlp.init() after adding the hidden layers.

Best regards

Ulf

**Comment by openSourceBugs** [comment]
Is there a way to see how much progress the training is taking?  I have a training set of size ~2500, 2 hidden layers of size 2 each layer, and inputs and outputs of length 1.  Max error is 0.05.  It is still not done after 4 hours.
